server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml image/svg+xml;
    gzip_disable "MSIE [1-6]\.";

    # Proxy para el Backend Go
    location /api/ {
        proxy_pass http://backend:8090/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Tamaño maximo de archivo a subir (50MB) para no bloquear requests grandes
        client_max_body_size 50M;
    }

    # SPA fallbacks 
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache de estaticos
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|avif|webp)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }
}
